// Generated by gencpp from file spencer_detected_person_association/LookupTrackIds.msg
// DO NOT EDIT!


#ifndef SPENCER_DETECTED_PERSON_ASSOCIATION_MESSAGE_LOOKUPTRACKIDS_H
#define SPENCER_DETECTED_PERSON_ASSOCIATION_MESSAGE_LOOKUPTRACKIDS_H

#include <ros/service_traits.h>


#include <spencer_detected_person_association/LookupTrackIdsRequest.h>
#include <spencer_detected_person_association/LookupTrackIdsResponse.h>


namespace spencer_detected_person_association
{

struct LookupTrackIds
{

typedef LookupTrackIdsRequest Request;
typedef LookupTrackIdsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LookupTrackIds
} // namespace spencer_detected_person_association


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spencer_detected_person_association::LookupTrackIds > {
  static const char* value()
  {
    return "fdbfb9d136dcf8dca2f9e4ae81a993ad";
  }

  static const char* value(const ::spencer_detected_person_association::LookupTrackIds&) { return value(); }
};

template<>
struct DataType< ::spencer_detected_person_association::LookupTrackIds > {
  static const char* value()
  {
    return "spencer_detected_person_association/LookupTrackIds";
  }

  static const char* value(const ::spencer_detected_person_association::LookupTrackIds&) { return value(); }
};


// service_traits::MD5Sum< ::spencer_detected_person_association::LookupTrackIdsRequest> should match 
// service_traits::MD5Sum< ::spencer_detected_person_association::LookupTrackIds > 
template<>
struct MD5Sum< ::spencer_detected_person_association::LookupTrackIdsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spencer_detected_person_association::LookupTrackIds >::value();
  }
  static const char* value(const ::spencer_detected_person_association::LookupTrackIdsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spencer_detected_person_association::LookupTrackIdsRequest> should match 
// service_traits::DataType< ::spencer_detected_person_association::LookupTrackIds > 
template<>
struct DataType< ::spencer_detected_person_association::LookupTrackIdsRequest>
{
  static const char* value()
  {
    return DataType< ::spencer_detected_person_association::LookupTrackIds >::value();
  }
  static const char* value(const ::spencer_detected_person_association::LookupTrackIdsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spencer_detected_person_association::LookupTrackIdsResponse> should match 
// service_traits::MD5Sum< ::spencer_detected_person_association::LookupTrackIds > 
template<>
struct MD5Sum< ::spencer_detected_person_association::LookupTrackIdsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spencer_detected_person_association::LookupTrackIds >::value();
  }
  static const char* value(const ::spencer_detected_person_association::LookupTrackIdsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spencer_detected_person_association::LookupTrackIdsResponse> should match 
// service_traits::DataType< ::spencer_detected_person_association::LookupTrackIds > 
template<>
struct DataType< ::spencer_detected_person_association::LookupTrackIdsResponse>
{
  static const char* value()
  {
    return DataType< ::spencer_detected_person_association::LookupTrackIds >::value();
  }
  static const char* value(const ::spencer_detected_person_association::LookupTrackIdsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPENCER_DETECTED_PERSON_ASSOCIATION_MESSAGE_LOOKUPTRACKIDS_H
