(cl:defpackage rwth_perception_people_msgs-msg
  (:use )
  (:export
   "<ANNOTATEDFRAME>"
   "ANNOTATEDFRAME"
   "<ANNOTATION>"
   "ANNOTATION"
   "<GROUNDHOGDETECTIONS>"
   "GROUNDHOGDETECTIONS"
   "<GROUNDPLANE>"
   "GROUNDPLANE"
   "<PEDESTRIANLOCATIONS>"
   "PEDESTRIANLOCATIONS"
   "<PEDESTRIANTRACKING>"
   "PEDESTRIANTRACKING"
   "<PEDESTRIANTRACKINGARRAY>"
   "PEDESTRIANTRACKINGARRAY"
   "<UPPERBODYDETECTOR>"
   "UPPERBODYDETECTOR"
   "<VISUALODOMETRY>"
   "VISUALODOMETRY"
  ))

