// Generated by gencpp from file actor_services/SetPose.msg
// DO NOT EDIT!


#ifndef ACTOR_SERVICES_MESSAGE_SETPOSE_H
#define ACTOR_SERVICES_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <actor_services/SetPoseRequest.h>
#include <actor_services/SetPoseResponse.h>


namespace actor_services
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace actor_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::actor_services::SetPose > {
  static const char* value()
  {
    return "d6701dc5a74a339cdbcd7f9e473eadfa";
  }

  static const char* value(const ::actor_services::SetPose&) { return value(); }
};

template<>
struct DataType< ::actor_services::SetPose > {
  static const char* value()
  {
    return "actor_services/SetPose";
  }

  static const char* value(const ::actor_services::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::actor_services::SetPoseRequest> should match 
// service_traits::MD5Sum< ::actor_services::SetPose > 
template<>
struct MD5Sum< ::actor_services::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::actor_services::SetPose >::value();
  }
  static const char* value(const ::actor_services::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::actor_services::SetPoseRequest> should match 
// service_traits::DataType< ::actor_services::SetPose > 
template<>
struct DataType< ::actor_services::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::actor_services::SetPose >::value();
  }
  static const char* value(const ::actor_services::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::actor_services::SetPoseResponse> should match 
// service_traits::MD5Sum< ::actor_services::SetPose > 
template<>
struct MD5Sum< ::actor_services::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::actor_services::SetPose >::value();
  }
  static const char* value(const ::actor_services::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::actor_services::SetPoseResponse> should match 
// service_traits::DataType< ::actor_services::SetPose > 
template<>
struct DataType< ::actor_services::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::actor_services::SetPose >::value();
  }
  static const char* value(const ::actor_services::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTOR_SERVICES_MESSAGE_SETPOSE_H
