// Generated by gencpp from file rwth_perception_people_msgs/PedestrianTrackingArray.msg
// DO NOT EDIT!


#ifndef RWTH_PERCEPTION_PEOPLE_MSGS_MESSAGE_PEDESTRIANTRACKINGARRAY_H
#define RWTH_PERCEPTION_PEOPLE_MSGS_MESSAGE_PEDESTRIANTRACKINGARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rwth_perception_people_msgs/PedestrianTracking.h>

namespace rwth_perception_people_msgs
{
template <class ContainerAllocator>
struct PedestrianTrackingArray_
{
  typedef PedestrianTrackingArray_<ContainerAllocator> Type;

  PedestrianTrackingArray_()
    : header()
    , pedestrians()  {
    }
  PedestrianTrackingArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pedestrians(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::rwth_perception_people_msgs::PedestrianTracking_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rwth_perception_people_msgs::PedestrianTracking_<ContainerAllocator> >::other >  _pedestrians_type;
  _pedestrians_type pedestrians;





  typedef boost::shared_ptr< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> const> ConstPtr;

}; // struct PedestrianTrackingArray_

typedef ::rwth_perception_people_msgs::PedestrianTrackingArray_<std::allocator<void> > PedestrianTrackingArray;

typedef boost::shared_ptr< ::rwth_perception_people_msgs::PedestrianTrackingArray > PedestrianTrackingArrayPtr;
typedef boost::shared_ptr< ::rwth_perception_people_msgs::PedestrianTrackingArray const> PedestrianTrackingArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rwth_perception_people_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'rwth_perception_people_msgs': ['/home/wwh/qqq/src/spencer_people_tracking/messages/rwth_perception_people_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9f67479ca0db5489cca876d9f98fd50";
  }

  static const char* value(const ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9f67479ca0db548ULL;
  static const uint64_t static_value2 = 0x9cca876d9f98fd50ULL;
};

template<class ContainerAllocator>
struct DataType< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rwth_perception_people_msgs/PedestrianTrackingArray";
  }

  static const char* value(const ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
PedestrianTracking[] pedestrians\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: rwth_perception_people_msgs/PedestrianTracking\n\
Header header\n\
# position projected on the GP in world coordinates\n\
float64[] traj_x \n\
float64[] traj_y \n\
float64[] traj_z\n\
# position projected on the GP in camera coordinates\n\
float64[] traj_x_camera \n\
float64[] traj_y_camera \n\
float64[] traj_z_camera \n\
float64[] dir 	\n\
float64 speed 	\n\
int64 id  \n\
float64 score\n\
";
  }

  static const char* value(const ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pedestrians);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PedestrianTrackingArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rwth_perception_people_msgs::PedestrianTrackingArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pedestrians[]" << std::endl;
    for (size_t i = 0; i < v.pedestrians.size(); ++i)
    {
      s << indent << "  pedestrians[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rwth_perception_people_msgs::PedestrianTracking_<ContainerAllocator> >::stream(s, indent + "    ", v.pedestrians[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RWTH_PERCEPTION_PEOPLE_MSGS_MESSAGE_PEDESTRIANTRACKINGARRAY_H
