(cl:defpackage spencer_detected_person_association-srv
  (:use )
  (:export
   "LOOKUPTRACKID"
   "<LOOKUPTRACKID-REQUEST>"
   "LOOKUPTRACKID-REQUEST"
   "<LOOKUPTRACKID-RESPONSE>"
   "LOOKUPTRACKID-RESPONSE"
   "LOOKUPTRACKIDS"
   "<LOOKUPTRACKIDS-REQUEST>"
   "LOOKUPTRACKIDS-REQUEST"
   "<LOOKUPTRACKIDS-RESPONSE>"
   "LOOKUPTRACKIDS-RESPONSE"
  ))

