// Generated by gencpp from file qq/Num.msg
// DO NOT EDIT!


#ifndef QQ_MESSAGE_NUM_H
#define QQ_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qq
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : age(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : age(0)  {
  (void)_alloc;
    }



   typedef uint8_t _age_type;
  _age_type age;





  typedef boost::shared_ptr< ::qq::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qq::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::qq::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::qq::Num > NumPtr;
typedef boost::shared_ptr< ::qq::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qq::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qq::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qq

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'qq': ['/home/wwh/qqq/src/qq/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qq::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qq::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qq::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qq::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qq::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qq::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qq::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3419afdf362438ee3543a542267b428";
  }

  static const char* value(const ::qq::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3419afdf362438eULL;
  static const uint64_t static_value2 = 0xe3543a542267b428ULL;
};

template<class ContainerAllocator>
struct DataType< ::qq::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qq/Num";
  }

  static const char* value(const ::qq::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qq::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 age\n\
";
  }

  static const char* value(const ::qq::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qq::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qq::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qq::Num_<ContainerAllocator>& v)
  {
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QQ_MESSAGE_NUM_H
