// Generated by gencpp from file spencer_bagfile_tools/AdditionalOdometryData.msg
// DO NOT EDIT!


#ifndef SPENCER_BAGFILE_TOOLS_MESSAGE_ADDITIONALODOMETRYDATA_H
#define SPENCER_BAGFILE_TOOLS_MESSAGE_ADDITIONALODOMETRYDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace spencer_bagfile_tools
{
template <class ContainerAllocator>
struct AdditionalOdometryData_
{
  typedef AdditionalOdometryData_<ContainerAllocator> Type;

  AdditionalOdometryData_()
    : header()
    , hardwareTimestamp(0)
    , totalDistance(0.0)
    , theta(0.0)
    , ticksLeft(0)
    , ticksRight(0)
    , calibOverallMultiplier(0.0)
    , calibLeftEncMultiplier(0.0)  {
    }
  AdditionalOdometryData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , hardwareTimestamp(0)
    , totalDistance(0.0)
    , theta(0.0)
    , ticksLeft(0)
    , ticksRight(0)
    , calibOverallMultiplier(0.0)
    , calibLeftEncMultiplier(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _hardwareTimestamp_type;
  _hardwareTimestamp_type hardwareTimestamp;

   typedef double _totalDistance_type;
  _totalDistance_type totalDistance;

   typedef double _theta_type;
  _theta_type theta;

   typedef int64_t _ticksLeft_type;
  _ticksLeft_type ticksLeft;

   typedef int64_t _ticksRight_type;
  _ticksRight_type ticksRight;

   typedef double _calibOverallMultiplier_type;
  _calibOverallMultiplier_type calibOverallMultiplier;

   typedef double _calibLeftEncMultiplier_type;
  _calibLeftEncMultiplier_type calibLeftEncMultiplier;





  typedef boost::shared_ptr< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> const> ConstPtr;

}; // struct AdditionalOdometryData_

typedef ::spencer_bagfile_tools::AdditionalOdometryData_<std::allocator<void> > AdditionalOdometryData;

typedef boost::shared_ptr< ::spencer_bagfile_tools::AdditionalOdometryData > AdditionalOdometryDataPtr;
typedef boost::shared_ptr< ::spencer_bagfile_tools::AdditionalOdometryData const> AdditionalOdometryDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spencer_bagfile_tools

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'spencer_bagfile_tools': ['/home/wwh/qqq/src/spencer_people_tracking/utils/spencer_bagfile_tools/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab677b3c60eb604fa8c19025b90f80c1";
  }

  static const char* value(const ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab677b3c60eb604fULL;
  static const uint64_t static_value2 = 0xa8c19025b90f80c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spencer_bagfile_tools/AdditionalOdometryData";
  }

  static const char* value(const ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header # message header\n\
\n\
uint64 hardwareTimestamp # milliseconds in hardware time since power-on\n\
\n\
float64 totalDistance # total absolute distance travelled so far (i.e. 10m forward, 10m backward => 20m)\n\
float64 theta # current theta angle in radians\n\
\n\
int64 ticksLeft # raw ticks of left encoder\n\
int64 ticksRight # raw ticks of right encoder\n\
\n\
float64 calibOverallMultiplier # calibration factor applied to both encoders' raw ticks\n\
float64 calibLeftEncMultiplier # calibration factor applied to only the left encoders' raw ticks, in addition to calibOverallMultiplier\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.hardwareTimestamp);
      stream.next(m.totalDistance);
      stream.next(m.theta);
      stream.next(m.ticksLeft);
      stream.next(m.ticksRight);
      stream.next(m.calibOverallMultiplier);
      stream.next(m.calibLeftEncMultiplier);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AdditionalOdometryData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spencer_bagfile_tools::AdditionalOdometryData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "hardwareTimestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.hardwareTimestamp);
    s << indent << "totalDistance: ";
    Printer<double>::stream(s, indent + "  ", v.totalDistance);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "ticksLeft: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ticksLeft);
    s << indent << "ticksRight: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ticksRight);
    s << indent << "calibOverallMultiplier: ";
    Printer<double>::stream(s, indent + "  ", v.calibOverallMultiplier);
    s << indent << "calibLeftEncMultiplier: ";
    Printer<double>::stream(s, indent + "  ", v.calibLeftEncMultiplier);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPENCER_BAGFILE_TOOLS_MESSAGE_ADDITIONALODOMETRYDATA_H
